apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: {{ .Values.requirements.capacityType.values }}
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: {{ .Values.requirements.instanceType.values }}
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: {{ .Values.requirements.zones.values }}
  limits:
    resources:
      cpu: {{ .Values.limits.resources.cpu }}
      memory: {{ .Values.limits.resources.memory }}
  provider:
    subnetSelector:
      karpenter.sh/discovery: {{ .Values.cluster.name }}
    securityGroupSelector:
      karpenter.sh/discovery: {{ .Values.cluster.name }}
  ttlSecondsAfterEmpty: 30